### ISSUE TITLE
Linebreaks in cpfuncs

### ISSUE THREAD

**Issue by jcoo092** [jcoo092/LaTeX-cP-systems#15]
Somewhat related to #5 but not quite the same.  The solution to #3, introduced by the pull request #14, breaks the capability of performing line breaks inside `cpfunc` macros.  You can include `newline` and `linebreak` macros inside `cpfunc`s, but the latter macros seem to be ignored, best as I can tell.  Using `\\` causes compilation errors.

I'm not sure what the solution is, but it would be good to re-enable the capability since sometimes there isn't really anything for it but to break a `cpfunc` across multiple lines.
